version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONBUFFERED: 1
    depends_on:
      - postgres
      - redis
    networks:
      - bot-net

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${pg_user}
      POSTGRES_PASSWORD: ${pg_password}
      POSTGRES_DB: ${pg_db}
    volumes:
      - ./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - bot-net

  redis:
    image: redis:7
    restart: always
    networks:
      - bot-net

networks:
  bot-net:
    driver: bridge
